[package]
name = "ffmpeg-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
ffmpeg-next = "*"

rust-extensions = { tag = "0.1.5", git = "https://github.com/MyJetTools/rust-extensions.git", features = [
    "with-tokio",
] }


tokio = { version = "*", features = ["fs"] }
lazy_static = "*"
